package com.itgowo.actionserver.view;

import com.itgowo.actionserver.ServerManager;

import javax.swing.*;
import java.awt.*;

public class LogWindow {
    public JTextPane textPane1;
    public JPanel panel1;
    private StringBuilder builder = new StringBuilder();


    public LogWindow() {

        ServerManager.setOnErrorListener(new ServerManager.onErrorListener() {
            @Override
            public void onError(Exception e) {
                builder.append(e.getMessage());
                if (builder.length() > 1024 * 1024 * 4) {
                    builder.setLength(1024 * 1024 * 3);
                }
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        textPane1.setText(builder.toString());
                    }
                });
            }
        });
    }

    public static void showLogWindow() {
        JFrame frame = new JFrame("LogWindow By 卢建超");
        frame.setContentPane(new LogWindow().panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        textPane1 = new JTextPane();
        panel1.add(textPane1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
